# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

sudo: required
cache: packages

r: bioc-devel

r_github_packages:
 - hadley/devtools#1263
 - rte-antares-rpackage/antaresRead@develop
 - rte-antares-rpackage/antaresProcessing


before_install:
- Rscript -e 'c(physical = parallel::detectCores(logical = FALSE), logical = parallel::detectCores())'

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
