# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

sudo: false
cache: packages

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

install:
  - ./travis-tool.sh install_r zlibbioc
  - ./travis-tool.sh install_r rhdf5
