# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

sudo: required
cache: packages

r_github_packages:
 - hadley/devtools#1263
 - Bioconductor-mirror/zlibbioc
 - Bioconductor-mirror/rhdf5
 - rte-antares-rpackage/antaresProcessing


r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
