# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

sudo: false
cache: packages


install:
  - ./travis-tool.sh install_bioc zlibbioc
  - ./travis-tool.sh install_bioc rhdf5

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
