# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

sudo: required
cache: packages

r: bioc-devel

r_github_packages:
 - hadley/devtools#1263
 - rte-antares-rpackage/antaresRead@develop
 - rte-antares-rpackage/antaresProcessing@develop

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
